### base config ###
full_field: &FULL_FIELD
  loss: 'l2'
  lr: 1E-3
  scheduler: 'ReduceLROnPlateau'
  num_data_workers: 4
  dt: 1 # how many timesteps ahead the model will predict
  n_history: 0 #how many previous timesteps to consider
  prediction_type: 'iterative'
  # prediction_length: 49 #applicable only if prediction_type == 'iterative'
  n_initial_conditions: 1 #applicable only if prediction_type == 'iterative'
  ics_type: "default"
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  maskpath: None
  perturb: !!bool False
  add_grid: !!bool False
  N_grid_channels: 0
  gridtype: 'sinusoidal' #options 'sinusoidal' or 'linear'
  roll: !!bool False
  max_epochs: 50
  batch_size: 64

  #afno hyperparams
  num_blocks: 8
  nettype: 'afno'
  patch_size: 2
  # embed_dim: 312
  # depth: 12
  # width: 56
  # modes: 32
  #options default, residual
  target: 'default' 
  in_channels: [0,1]
  out_channels: [0,1] #must be same as in_channels if prediction_type == 'iterative'
  normalization: 'zscore' #options zscore (minmax not supported) 
  train_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/train'
  valid_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/test'
  inf_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/test' # test set path for inference
  exp_dir: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/output'
  time_means_path:   '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/time_means.npy'
  global_means_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/global_means.npy'
  global_stds_path:  '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/global_stds.npy'

  orography: !!bool False
  orography_path: None

  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True

  enable_nhwc: !!bool False
  optimizer_type: 'Adam' #'FusedAdam'
  crop_size_x: None
  crop_size_y: None

  two_step_training: !!bool False
  plot_animations: !!bool False

  add_noise: !!bool False
  noise_std: 0

afno_backbone: &backbone
  <<: *FULL_FIELD
  log_to_wandb: !!bool True
  lr: 5E-4
  batch_size: 64
  max_epochs: 3
  scheduler: 'CosineAnnealingLR'
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
  orography: !!bool False
  orography_path: None 
  exp_dir: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/output'
  train_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/train'
  valid_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/test'
  inf_data_path:   '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/test'
  time_means_path:   '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/time_means.npy'
  global_means_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/global_means.npy'
  global_stds_path:  '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/global_stds.npy'

afno_backbone_orography: &backbone_orography 
  <<: *backbone
  orography: !!bool False
  orography_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/static/orography.h5'

afno_backbone_finetune: 
  <<: *backbone
  lr: 1E-4
  batch_size: 64
  log_to_wandb: !!bool True
  max_epochs: 20
  pretrained: !!bool True
  two_step_training: !!bool True
  pretrained_ckpt_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/HRRR/afno_backbone/0/training_checkpoints/best_ckpt.tar'

perturbations:
  <<: *backbone
  lr: 1E-4
  batch_size: 64
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  pretrained_ckpt_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/0/training_checkpoints/best_ckpt.tar'
  prediction_length: 49
  ics_type: "default"
  n_perturbations: 100 
  save_channel: !bool True
  save_idx: 4
  save_raw_forecasts: !!bool False
  date_strings: ["2018-01-01 00:00:00"] 
  inference_file_tag: " "
  valid_data_path: '/autofs/nccs-svm1_proj/nwp501/grnydawn/data/RegionalWFN/dataset/test'
  perturb: !!bool True
  n_level: 0.3

### PRECIP ###
# precip: &precip
#   <<: *backbone
#   in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
#   out_channels: [0]
#   nettype: 'afno'
#   nettype_wind: 'afno'
#   log_to_wandb: !!bool True
#   lr: 2.5E-4
#   batch_size: 64
#   max_epochs: 25
#   precip: '/pscratch/sd/p/pharring/ERA5/precip/total_precipitation'
#   time_means_path_tp: '/pscratch/sd/p/pharring/ERA5/precip/total_precipitation/time_means.npy'
#   model_wind_path: '/pscratch/sd/s/shas1693/results/era5_wind/afno_backbone_finetune/0/training_checkpoints/best_ckpt.tar'
#   precip_eps: !!float 1e-5

